insert into car_data (id, car_make, car_model, car_model_year) values (1, 'Toyota', 'Solara', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (2, 'Toyota', 'Prius v', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (3, 'Buick', 'Lucerne', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (4, 'Volvo', 'V70', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (5, 'Lexus', 'LX', 2013);
insert into car_data (id, car_make, car_model, car_model_year) values (6, 'Nissan', 'Rogue', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (7, 'Toyota', 'Sienna', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (8, 'Audi', 'A4', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (9, 'Ford', 'Econoline E250', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (10, 'Chevrolet', 'Cavalier', 1992);
insert into car_data (id, car_make, car_model, car_model_year) values (11, 'Pontiac', 'GTO', 1964);
insert into car_data (id, car_make, car_model, car_model_year) values (12, 'Pontiac', 'Gemini', 1987);
insert into car_data (id, car_make, car_model, car_model_year) values (13, 'Lexus', 'ES', 1999);
insert into car_data (id, car_make, car_model, car_model_year) values (14, 'Dodge', 'D250 Club', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (15, 'Chevrolet', 'Express 3500', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (16, 'Dodge', 'Ram 3500', 1997);
insert into car_data (id, car_make, car_model, car_model_year) values (17, 'Lexus', 'IS F', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (18, 'Buick', 'Rainier', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (19, 'Ford', 'Transit Connect', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (20, 'Buick', 'Century', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (21, 'Ford', 'Mustang', 1974);
insert into car_data (id, car_make, car_model, car_model_year) values (22, 'Pontiac', 'Montana', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (23, 'Aston Martin', 'Vantage', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (24, 'Dodge', 'Dakota Club', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (25, 'Toyota', 'Land Cruiser', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (26, 'GMC', 'Canyon', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (27, 'Mercury', 'Cougar', 1984);
insert into car_data (id, car_make, car_model, car_model_year) values (28, 'Buick', 'Skylark', 1995);
insert into car_data (id, car_make, car_model, car_model_year) values (29, 'Lexus', 'LS', 1997);
insert into car_data (id, car_make, car_model, car_model_year) values (30, 'Land Rover', 'Freelander', 2001);
insert into car_data (id, car_make, car_model, car_model_year) values (31, 'Porsche', '911', 1987);
insert into car_data (id, car_make, car_model, car_model_year) values (32, 'Chevrolet', 'Express 1500', 1999);
insert into car_data (id, car_make, car_model, car_model_year) values (33, 'Volvo', 'S80', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (34, 'Chevrolet', 'Express 3500', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (35, 'Hyundai', 'Genesis', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (36, 'Maybach', 'Landaulet', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (37, 'Nissan', 'Rogue', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (38, 'Ford', 'Explorer', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (39, 'Toyota', 'Avalon', 1996);
insert into car_data (id, car_make, car_model, car_model_year) values (40, 'Ford', 'F150', 1997);
insert into car_data (id, car_make, car_model, car_model_year) values (41, 'Chevrolet', 'Suburban 1500', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (42, 'Mercedes-Benz', 'E-Class', 1989);
insert into car_data (id, car_make, car_model, car_model_year) values (43, 'Dodge', 'Ram', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (44, 'Buick', 'Century', 1999);
insert into car_data (id, car_make, car_model, car_model_year) values (45, 'Pontiac', 'Grand Am', 1996);
insert into car_data (id, car_make, car_model, car_model_year) values (46, 'Buick', 'Century', 1986);
insert into car_data (id, car_make, car_model, car_model_year) values (47, 'Mercedes-Benz', 'G-Class', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (48, 'Chevrolet', 'Venture', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (49, 'Nissan', 'Altima', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (50, 'Mazda', 'Protege', 1997);
insert into car_data (id, car_make, car_model, car_model_year) values (51, 'Lincoln', 'Continental Mark VII', 1988);
insert into car_data (id, car_make, car_model, car_model_year) values (52, 'Dodge', 'Grand Caravan', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (53, 'Toyota', 'Sequoia', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (54, 'Ford', 'Crown Victoria', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (55, 'Nissan', 'Frontier', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (56, 'Isuzu', 'Space', 1992);
insert into car_data (id, car_make, car_model, car_model_year) values (57, 'Audi', 'A4', 1999);
insert into car_data (id, car_make, car_model, car_model_year) values (58, 'Buick', 'Century', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (59, 'Toyota', 'TundraMax', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (60, 'Mitsubishi', 'Eclipse', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (61, 'Honda', 'Civic', 1995);
insert into car_data (id, car_make, car_model, car_model_year) values (62, 'Ferrari', '612 Scaglietti', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (63, 'BMW', 'Z4 M', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (64, 'Honda', 'Odyssey', 1996);
insert into car_data (id, car_make, car_model, car_model_year) values (65, 'Nissan', 'Murano', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (66, 'Ford', 'F-Series', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (67, 'Mitsubishi', 'RVR', 1994);
insert into car_data (id, car_make, car_model, car_model_year) values (68, 'Chevrolet', 'Cavalier', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (69, 'Jeep', 'Wrangler', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (70, 'GMC', 'Acadia', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (71, 'Toyota', '4Runner', 1996);
insert into car_data (id, car_make, car_model, car_model_year) values (72, 'Hyundai', 'Azera', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (73, 'Volvo', 'C70', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (74, 'Oldsmobile', 'Alero', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (75, 'Dodge', 'Ram Van 1500', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (76, 'Chrysler', 'Pacifica', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (77, 'Dodge', 'Caravan', 1995);
insert into car_data (id, car_make, car_model, car_model_year) values (78, 'Lincoln', 'Town Car', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (79, 'Toyota', 'Avalon', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (80, 'Chevrolet', 'Camaro', 1972);
insert into car_data (id, car_make, car_model, car_model_year) values (81, 'GMC', 'Savana', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (82, 'Mercury', 'Topaz', 1989);
insert into car_data (id, car_make, car_model, car_model_year) values (83, 'GMC', 'Savana 3500', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (84, 'Ford', 'E250', 1984);
insert into car_data (id, car_make, car_model, car_model_year) values (85, 'Mercury', 'Grand Marquis', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (86, 'Dodge', 'Dakota', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (87, 'Isuzu', 'Amigo', 1994);
insert into car_data (id, car_make, car_model, car_model_year) values (88, 'Honda', 'Ridgeline', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (89, 'Bentley', 'Continental Flying Spur', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (90, 'Ford', 'Mustang', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (91, 'Chevrolet', 'Express', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (92, 'Dodge', 'Ram 3500 Club', 1997);
insert into car_data (id, car_make, car_model, car_model_year) values (93, 'Dodge', 'Ram Wagon B350', 1992);
insert into car_data (id, car_make, car_model, car_model_year) values (94, 'Buick', 'Park Avenue', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (95, 'Ford', 'Mustang', 1985);
insert into car_data (id, car_make, car_model, car_model_year) values (96, 'Chrysler', 'PT Cruiser', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (97, 'Volkswagen', 'Tiguan', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (98, 'Mazda', 'Miata MX-5', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (99, 'Cadillac', 'SRX', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (100, 'Mercury', 'Cougar', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (101, 'Kia', 'Rio', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (102, 'Nissan', 'Titan', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (103, 'Mazda', 'B2500', 2001);
insert into car_data (id, car_make, car_model, car_model_year) values (104, 'Mazda', 'Mazdaspeed 3', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (105, 'Pontiac', 'Firebird', 1992);
insert into car_data (id, car_make, car_model, car_model_year) values (106, 'Saturn', 'S-Series', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (107, 'Volkswagen', 'Jetta', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (108, 'Ford', 'F450', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (109, 'Audi', '100', 1990);
insert into car_data (id, car_make, car_model, car_model_year) values (110, 'Saturn', 'S-Series', 1992);
insert into car_data (id, car_make, car_model, car_model_year) values (111, 'Ford', 'Fairlane', 1966);
insert into car_data (id, car_make, car_model, car_model_year) values (112, 'GMC', 'Sierra 2500', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (113, 'Chevrolet', 'Suburban 2500', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (114, 'Honda', 'S2000', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (115, 'Dodge', 'Dakota', 2001);
insert into car_data (id, car_make, car_model, car_model_year) values (116, 'Audi', 'riolet', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (117, 'Kia', 'Sedona', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (118, 'Chevrolet', 'Silverado 2500', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (119, 'Maserati', 'Quattroporte', 1985);
insert into car_data (id, car_make, car_model, car_model_year) values (120, 'Chevrolet', 'Camaro', 2001);
insert into car_data (id, car_make, car_model, car_model_year) values (121, 'Hyundai', 'Sonata', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (122, 'Mazda', 'GLC', 1984);
insert into car_data (id, car_make, car_model, car_model_year) values (123, 'Pontiac', 'Grand Prix', 1989);
insert into car_data (id, car_make, car_model, car_model_year) values (124, 'Toyota', 'Camry Hybrid', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (125, 'Cadillac', 'Seville', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (126, 'Porsche', 'Boxster', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (127, 'Ford', 'Econoline E350', 1996);
insert into car_data (id, car_make, car_model, car_model_year) values (128, 'Dodge', 'Ram Van 2500', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (129, 'Cadillac', 'XLR', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (130, 'Ford', 'Windstar', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (131, 'Dodge', 'Ram Wagon B150', 1994);
insert into car_data (id, car_make, car_model, car_model_year) values (132, 'Dodge', 'Durango', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (133, 'Oldsmobile', 'Intrigue', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (134, 'Pontiac', 'Grand Prix', 1997);
insert into car_data (id, car_make, car_model, car_model_year) values (135, 'Ford', 'Ranger', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (136, 'Isuzu', 'VehiCROSS', 2001);
insert into car_data (id, car_make, car_model, car_model_year) values (137, 'Ford', 'Focus', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (138, 'Dodge', 'Ram 2500', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (139, 'Lexus', 'IS-F', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (140, 'Chrysler', 'Cirrus', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (141, 'Volkswagen', 'Passat', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (142, 'Mercedes-Benz', 'S-Class', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (143, 'Honda', 'CR-X', 1988);
insert into car_data (id, car_make, car_model, car_model_year) values (144, 'Acura', 'ZDX', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (145, 'Mazda', 'CX-9', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (146, 'Lincoln', 'MKZ', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (147, 'Dodge', 'Dakota', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (148, 'Chevrolet', 'Astro', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (149, 'Buick', 'Park Avenue', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (150, 'Mercedes-Benz', 'SL-Class', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (151, 'Chrysler', 'Prowler', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (152, 'Chevrolet', 'Express 3500', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (153, 'Ford', 'Explorer', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (154, 'Pontiac', 'Grand Prix', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (155, 'Acura', 'TL', 2005);
insert into car_data (id, car_make, car_model, car_model_year) values (156, 'Chrysler', 'LHS', 1999);
insert into car_data (id, car_make, car_model, car_model_year) values (157, 'Chevrolet', 'Silverado', 2001);
insert into car_data (id, car_make, car_model, car_model_year) values (158, 'Chevrolet', 'G-Series G20', 1994);
insert into car_data (id, car_make, car_model, car_model_year) values (159, 'Chevrolet', 'Astro', 1995);
insert into car_data (id, car_make, car_model, car_model_year) values (160, 'Dodge', 'Neon', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (161, 'Honda', 'Civic', 1995);
insert into car_data (id, car_make, car_model, car_model_year) values (162, 'Ford', 'Festiva', 1992);
insert into car_data (id, car_make, car_model, car_model_year) values (163, 'Mitsubishi', 'Truck', 1990);
insert into car_data (id, car_make, car_model, car_model_year) values (164, 'Smart', 'Fortwo', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (165, 'Mercury', 'Mystique', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (166, 'Chevrolet', 'Silverado 3500', 2001);
insert into car_data (id, car_make, car_model, car_model_year) values (167, 'Land Rover', 'LR2', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (168, 'Hummer', 'H1', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (169, 'Mercury', 'Cougar', 1990);
insert into car_data (id, car_make, car_model, car_model_year) values (170, 'Land Rover', 'Range Rover', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (171, 'Volkswagen', 'Cabriolet', 1989);
insert into car_data (id, car_make, car_model, car_model_year) values (172, 'Jaguar', 'S-Type', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (173, 'Hyundai', 'Santa Fe', 2005);
insert into car_data (id, car_make, car_model, car_model_year) values (174, 'Volvo', 'S40', 2005);
insert into car_data (id, car_make, car_model, car_model_year) values (175, 'Nissan', 'Murano', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (176, 'BMW', 'Z8', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (177, 'Buick', 'Enclave', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (178, 'Mercedes-Benz', 'CLS-Class', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (179, 'Hyundai', 'Santa Fe', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (180, 'Pontiac', 'Sunbird', 1991);
insert into car_data (id, car_make, car_model, car_model_year) values (181, 'Cadillac', 'Eldorado', 1997);
insert into car_data (id, car_make, car_model, car_model_year) values (182, 'Honda', 'Accord', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (183, 'Pontiac', 'Firebird Formula', 1992);
insert into car_data (id, car_make, car_model, car_model_year) values (184, 'Chrysler', 'Sebring', 1996);
insert into car_data (id, car_make, car_model, car_model_year) values (185, 'Mitsubishi', 'Starion', 1985);
insert into car_data (id, car_make, car_model, car_model_year) values (186, 'Ford', 'Explorer Sport', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (187, 'Dodge', 'Aries', 1981);
insert into car_data (id, car_make, car_model, car_model_year) values (188, 'Chevrolet', 'G-Series 2500', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (189, 'Saturn', 'L-Series', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (190, 'Chevrolet', 'HHR', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (191, 'Porsche', '924 S', 1987);
insert into car_data (id, car_make, car_model, car_model_year) values (192, 'Isuzu', 'Oasis', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (193, 'Lexus', 'LX', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (194, 'Toyota', 'Tundra', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (195, 'Audi', '4000CS Quattro', 1986);
insert into car_data (id, car_make, car_model, car_model_year) values (196, 'Chevrolet', 'Express 3500', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (197, 'Mercedes-Benz', 'SL-Class', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (198, 'Jaguar', 'XK Series', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (199, 'Dodge', 'Ram Van 1500', 1996);
insert into car_data (id, car_make, car_model, car_model_year) values (200, 'Lamborghini', 'Murciélago', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (201, 'Mitsubishi', 'Lancer Evolution', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (202, 'Buick', 'Park Avenue', 1999);
insert into car_data (id, car_make, car_model, car_model_year) values (203, 'Chevrolet', 'Corvette', 1961);
insert into car_data (id, car_make, car_model, car_model_year) values (204, 'Volkswagen', 'Golf', 2005);
insert into car_data (id, car_make, car_model, car_model_year) values (205, 'MG', 'MGB', 1977);
insert into car_data (id, car_make, car_model, car_model_year) values (206, 'Mercury', 'Milan', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (207, 'Infiniti', 'EX', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (208, 'Volkswagen', 'Passat', 1995);
insert into car_data (id, car_make, car_model, car_model_year) values (209, 'Dodge', 'Dakota', 1995);
insert into car_data (id, car_make, car_model, car_model_year) values (210, 'Mercedes-Benz', 'E-Class', 1990);
insert into car_data (id, car_make, car_model, car_model_year) values (211, 'Citroën', 'CX', 1974);
insert into car_data (id, car_make, car_model, car_model_year) values (212, 'Lincoln', 'Navigator', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (213, 'Lexus', 'GS', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (214, 'Saturn', 'S-Series', 1996);
insert into car_data (id, car_make, car_model, car_model_year) values (215, 'Audi', 'A8', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (216, 'GMC', 'Canyon', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (217, 'Ford', 'Mustang', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (218, 'Buick', 'LeSabre', 2005);
insert into car_data (id, car_make, car_model, car_model_year) values (219, 'Pontiac', 'G6', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (220, 'BMW', '6 Series', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (221, 'Mazda', 'MPV', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (222, 'Mercury', 'Mountaineer', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (223, 'Ferrari', 'F430', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (224, 'Toyota', 'Tundra', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (225, 'Subaru', 'Legacy', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (226, 'Scion', 'tC', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (227, 'Jeep', 'Liberty', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (228, 'Dodge', 'Viper RT/10', 1995);
insert into car_data (id, car_make, car_model, car_model_year) values (229, 'Chevrolet', 'Express 1500', 1996);
insert into car_data (id, car_make, car_model, car_model_year) values (230, 'Toyota', 'Solara', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (231, 'Saturn', 'Astra', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (232, 'Pontiac', 'Torrent', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (233, 'Mitsubishi', 'Truck', 1990);
insert into car_data (id, car_make, car_model, car_model_year) values (234, 'Dodge', 'Ram 2500 Club', 1996);
insert into car_data (id, car_make, car_model, car_model_year) values (235, 'Pontiac', 'Bonneville', 1997);
insert into car_data (id, car_make, car_model, car_model_year) values (236, 'Chrysler', 'Crossfire', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (237, 'Dodge', 'Caravan', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (238, 'Plymouth', 'Grand Voyager', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (239, 'Nissan', 'Murano', 2005);
insert into car_data (id, car_make, car_model, car_model_year) values (240, 'Lexus', 'LX', 2001);
insert into car_data (id, car_make, car_model, car_model_year) values (241, 'Ford', 'Five Hundred', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (242, 'Ford', 'Aerostar', 1994);
insert into car_data (id, car_make, car_model, car_model_year) values (243, 'Chrysler', 'Town & Country', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (244, 'Hummer', 'H2 SUT', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (245, 'Pontiac', 'Firefly', 1987);
insert into car_data (id, car_make, car_model, car_model_year) values (246, 'Mazda', '929', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (247, 'Mercedes-Benz', 'C-Class', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (248, 'Honda', 'Civic', 1991);
insert into car_data (id, car_make, car_model, car_model_year) values (249, 'BMW', 'X5', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (250, 'Hyundai', 'Azera', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (251, 'Mitsubishi', 'Space', 1984);
insert into car_data (id, car_make, car_model, car_model_year) values (252, 'Chevrolet', 'Express 3500', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (253, 'Chevrolet', 'Camaro', 1985);
insert into car_data (id, car_make, car_model, car_model_year) values (254, 'Infiniti', 'I', 2001);
insert into car_data (id, car_make, car_model, car_model_year) values (255, 'Infiniti', 'G', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (256, 'Toyota', 'Echo', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (257, 'Mercedes-Benz', 'E-Class', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (258, 'Ford', 'Escort', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (259, 'Volvo', 'C30', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (260, 'Dodge', 'Journey', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (261, 'Chevrolet', 'TrailBlazer', 2005);
insert into car_data (id, car_make, car_model, car_model_year) values (262, 'Mazda', 'Mazda2', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (263, 'Cadillac', 'Sixty Special', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (264, 'Buick', 'Roadmaster', 1994);
insert into car_data (id, car_make, car_model, car_model_year) values (265, 'Toyota', 'Xtra', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (266, 'Volkswagen', 'Fox', 1988);
insert into car_data (id, car_make, car_model, car_model_year) values (267, 'Hummer', 'H2', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (268, 'GMC', 'Savana 3500', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (269, 'Ford', 'Explorer', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (270, 'Ford', 'Ranger', 1988);
insert into car_data (id, car_make, car_model, car_model_year) values (271, 'Lincoln', 'Continental', 1990);
insert into car_data (id, car_make, car_model, car_model_year) values (272, 'Ford', 'E-Series', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (273, 'Ford', 'Ranger', 1994);
insert into car_data (id, car_make, car_model, car_model_year) values (274, 'Toyota', 'Sequoia', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (275, 'Jaguar', 'XK Series', 1997);
insert into car_data (id, car_make, car_model, car_model_year) values (276, 'Toyota', 'Tacoma Xtra', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (277, 'Chevrolet', 'Lumina', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (278, 'Chevrolet', 'Aveo', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (279, 'Buick', 'LaCrosse', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (280, 'Mercury', 'Montego', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (281, 'Chevrolet', 'G-Series 3500', 1997);
insert into car_data (id, car_make, car_model, car_model_year) values (282, 'Pontiac', 'GTO', 1968);
insert into car_data (id, car_make, car_model, car_model_year) values (283, 'Ford', 'Mustang', 1994);
insert into car_data (id, car_make, car_model, car_model_year) values (284, 'Bentley', 'Continental GTC', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (285, 'Mitsubishi', 'Galant', 1994);
insert into car_data (id, car_make, car_model, car_model_year) values (286, 'Saturn', 'Sky', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (287, 'Mercedes-Benz', 'SLR McLaren', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (288, 'Honda', 'Civic', 1991);
insert into car_data (id, car_make, car_model, car_model_year) values (289, 'Mercury', 'Mariner', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (290, 'Land Rover', 'Defender Ice Edition', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (291, 'Pontiac', 'Fiero', 1986);
insert into car_data (id, car_make, car_model, car_model_year) values (292, 'Audi', 'S8', 2001);
insert into car_data (id, car_make, car_model, car_model_year) values (293, 'Dodge', 'Grand Caravan', 2001);
insert into car_data (id, car_make, car_model, car_model_year) values (294, 'Dodge', 'Ram Van B150', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (295, 'Isuzu', 'Hombre', 1999);
insert into car_data (id, car_make, car_model, car_model_year) values (296, 'BMW', '530', 2005);
insert into car_data (id, car_make, car_model, car_model_year) values (297, 'Mercedes-Benz', 'E-Class', 1997);
insert into car_data (id, car_make, car_model, car_model_year) values (298, 'Mazda', 'Mazda3', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (299, 'Nissan', 'Quest', 1997);
insert into car_data (id, car_make, car_model, car_model_year) values (300, 'Mitsubishi', 'Endeavor', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (301, 'Acura', 'CL', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (302, 'Acura', 'MDX', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (303, 'Dodge', 'Ram', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (304, 'BMW', 'X5', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (305, 'Aston Martin', 'Rapide', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (306, 'Dodge', 'Spirit', 1994);
insert into car_data (id, car_make, car_model, car_model_year) values (307, 'Volkswagen', 'Routan', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (308, 'Suzuki', 'SX4', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (309, 'GMC', 'Terrain', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (310, 'Volkswagen', 'New Beetle', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (311, 'GMC', 'Sierra 1500', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (312, 'Saturn', 'VUE', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (313, 'Audi', 'S4', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (314, 'Suzuki', 'Equator', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (315, 'Hyundai', 'Sonata', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (316, 'Aston Martin', 'Vanquish S', 2005);
insert into car_data (id, car_make, car_model, car_model_year) values (317, 'Chevrolet', 'Suburban 1500', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (318, 'Volvo', 'XC60', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (319, 'Ford', 'Thunderbird', 1972);
insert into car_data (id, car_make, car_model, car_model_year) values (320, 'Honda', 'Prelude', 1995);
insert into car_data (id, car_make, car_model, car_model_year) values (321, 'Acura', 'ZDX', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (322, 'Dodge', 'Grand Caravan', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (323, 'Dodge', 'Grand Caravan', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (324, 'Mazda', 'Mazda5', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (325, 'Infiniti', 'G', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (326, 'Hyundai', 'Azera', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (327, 'Mitsubishi', 'Eclipse', 1989);
insert into car_data (id, car_make, car_model, car_model_year) values (328, 'Suzuki', 'Vitara', 1999);
insert into car_data (id, car_make, car_model, car_model_year) values (329, 'Mitsubishi', 'Pajero', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (330, 'Nissan', 'Quest', 2005);
insert into car_data (id, car_make, car_model, car_model_year) values (331, 'Pontiac', 'Bonneville', 1964);
insert into car_data (id, car_make, car_model, car_model_year) values (332, 'Toyota', 'MR2', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (333, 'Mercury', 'Topaz', 1992);
insert into car_data (id, car_make, car_model, car_model_year) values (334, 'Lincoln', 'Continental', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (335, 'Audi', 'S8', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (336, 'Cadillac', 'Escalade ESV', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (337, 'Ford', 'Ranger', 1989);
insert into car_data (id, car_make, car_model, car_model_year) values (338, 'Volkswagen', 'Type 2', 1990);
insert into car_data (id, car_make, car_model, car_model_year) values (339, 'Nissan', 'Altima', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (340, 'Cadillac', 'CTS', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (341, 'Mercedes-Benz', '300SE', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (342, 'Volkswagen', 'rio', 1997);
insert into car_data (id, car_make, car_model, car_model_year) values (343, 'Jeep', 'Wrangler', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (344, 'Maybach', '57', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (345, 'Buick', 'Century', 1997);
insert into car_data (id, car_make, car_model, car_model_year) values (346, 'Subaru', 'Outback', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (347, 'Dodge', 'Spirit', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (348, 'GMC', 'Savana 3500', 2005);
insert into car_data (id, car_make, car_model, car_model_year) values (349, 'Mercedes-Benz', 'C-Class', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (350, 'Lincoln', 'Navigator L', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (351, 'Ram', '2500', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (352, 'Ford', 'Escape', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (353, 'Mitsubishi', 'Pajero', 1997);
insert into car_data (id, car_make, car_model, car_model_year) values (354, 'Audi', 'A8', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (355, 'Porsche', 'Carrera GT', 2005);
insert into car_data (id, car_make, car_model, car_model_year) values (356, 'Jeep', 'Grand Cherokee', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (357, 'Chevrolet', 'TrailBlazer', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (358, 'Chevrolet', 'Caprice Classic', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (359, 'Mitsubishi', 'Galant', 1995);
insert into car_data (id, car_make, car_model, car_model_year) values (360, 'Mercedes-Benz', 'CL-Class', 2005);
insert into car_data (id, car_make, car_model, car_model_year) values (361, 'Mitsubishi', 'Precis', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (362, 'Pontiac', '6000', 1985);
insert into car_data (id, car_make, car_model, car_model_year) values (363, 'BMW', '5 Series', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (364, 'Isuzu', 'Trooper', 1994);
insert into car_data (id, car_make, car_model, car_model_year) values (365, 'Mitsubishi', 'Eclipse', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (366, 'Dodge', 'Ram Van 3500', 1996);
insert into car_data (id, car_make, car_model, car_model_year) values (367, 'Alfa Romeo', 'Spider', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (368, 'Suzuki', 'SJ 410', 1984);
insert into car_data (id, car_make, car_model, car_model_year) values (369, 'Audi', 'TT', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (370, 'Hummer', 'H2', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (371, 'Infiniti', 'FX', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (372, 'GMC', 'Envoy', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (373, 'Chevrolet', 'S10', 1992);
insert into car_data (id, car_make, car_model, car_model_year) values (374, 'Jaguar', 'X-Type', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (375, 'Honda', 'Insight', 2005);
insert into car_data (id, car_make, car_model, car_model_year) values (376, 'Ford', 'Escort', 2001);
insert into car_data (id, car_make, car_model, car_model_year) values (377, 'Nissan', 'NV1500', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (378, 'Volkswagen', 'Type 2', 1989);
insert into car_data (id, car_make, car_model, car_model_year) values (379, 'Suzuki', 'Reno', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (380, 'Lexus', 'LS Hybrid', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (381, 'Volvo', 'XC70', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (382, 'Pontiac', 'Firebird', 2001);
insert into car_data (id, car_make, car_model, car_model_year) values (383, 'Dodge', 'Ram Van 2500', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (384, 'Hyundai', 'Elantra', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (385, 'Bentley', 'Continental', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (386, 'Suzuki', 'Equator', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (387, 'Mercedes-Benz', '300SL', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (388, 'Mazda', 'MX-5', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (389, 'Ford', 'GT500', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (390, 'Nissan', 'Frontier', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (391, 'GMC', 'Yukon', 2005);
insert into car_data (id, car_make, car_model, car_model_year) values (392, 'Mercedes-Benz', 'CL-Class', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (393, 'Jeep', 'Cherokee', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (394, 'Nissan', '300ZX', 1996);
insert into car_data (id, car_make, car_model, car_model_year) values (395, 'GMC', 'Sierra 3500', 2005);
insert into car_data (id, car_make, car_model, car_model_year) values (396, 'Toyota', 'Tundra', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (397, 'Mitsubishi', 'Endeavor', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (398, 'Oldsmobile', 'Achieva', 1992);
insert into car_data (id, car_make, car_model, car_model_year) values (399, 'Volkswagen', 'Jetta', 1992);
insert into car_data (id, car_make, car_model, car_model_year) values (400, 'Lexus', 'SC', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (401, 'Lincoln', 'Town Car', 1988);
insert into car_data (id, car_make, car_model, car_model_year) values (402, 'Chrysler', 'Prowler', 2001);
insert into car_data (id, car_make, car_model, car_model_year) values (403, 'Pontiac', 'G6', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (404, 'Mitsubishi', 'Eclipse', 1997);
insert into car_data (id, car_make, car_model, car_model_year) values (405, 'Ford', 'Escort', 1994);
insert into car_data (id, car_make, car_model, car_model_year) values (406, 'Chevrolet', 'Tahoe', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (407, 'Toyota', 'Avalon', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (408, 'GMC', 'Yukon XL 1500', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (409, 'Chevrolet', 'Aveo', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (410, 'Subaru', 'Outback Sport', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (411, 'Ford', 'F-Series Super Duty', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (412, 'Pontiac', 'Grand Prix', 1986);
insert into car_data (id, car_make, car_model, car_model_year) values (413, 'Kia', 'Amanti', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (414, 'GMC', 'Safari', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (415, 'BMW', 'M3', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (416, 'Oldsmobile', 'Bravada', 1992);
insert into car_data (id, car_make, car_model, car_model_year) values (417, 'Honda', 'Civic', 1999);
insert into car_data (id, car_make, car_model, car_model_year) values (418, 'Mazda', 'Mazda6', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (419, 'Mitsubishi', 'Starion', 1987);
insert into car_data (id, car_make, car_model, car_model_year) values (420, 'Mitsubishi', 'Expo LRV', 1996);
insert into car_data (id, car_make, car_model, car_model_year) values (421, 'Volkswagen', 'Beetle', 1967);
insert into car_data (id, car_make, car_model, car_model_year) values (422, 'Audi', 'S8', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (423, 'Chevrolet', 'Cobalt SS', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (424, 'Chevrolet', 'Suburban 2500', 2000);
insert into car_data (id, car_make, car_model, car_model_year) values (425, 'Mitsubishi', 'Cordia', 1987);
insert into car_data (id, car_make, car_model, car_model_year) values (426, 'BMW', 'Z4', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (427, 'Ford', 'Ranger', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (428, 'Volvo', 'C30', 2013);
insert into car_data (id, car_make, car_model, car_model_year) values (429, 'Chevrolet', 'Lumina', 1994);
insert into car_data (id, car_make, car_model, car_model_year) values (430, 'Suzuki', 'Kizashi', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (431, 'Dodge', 'Dakota Club', 1992);
insert into car_data (id, car_make, car_model, car_model_year) values (432, 'Toyota', 'Highlander', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (433, 'Toyota', 'Supra', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (434, 'Chevrolet', 'Express 1500', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (435, 'GMC', 'Sierra 3500', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (436, 'Nissan', 'Sentra', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (437, 'Mitsubishi', 'Lancer Evolution', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (438, 'Jeep', 'Grand Cherokee', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (439, 'Mercury', 'Sable', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (440, 'Hyundai', 'Equus', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (441, 'Chevrolet', 'Malibu', 2006);
insert into car_data (id, car_make, car_model, car_model_year) values (442, 'Buick', 'LeSabre', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (443, 'Ford', 'Ranger', 2005);
insert into car_data (id, car_make, car_model, car_model_year) values (444, 'Saturn', 'S-Series', 1997);
insert into car_data (id, car_make, car_model, car_model_year) values (445, 'Buick', 'Somerset', 1987);
insert into car_data (id, car_make, car_model, car_model_year) values (446, 'Toyota', 'Tacoma Xtra', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (447, 'Mercedes-Benz', 'E-Class', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (448, 'GMC', '3500 Club Coupe', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (449, 'Audi', 'A4', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (450, 'Lexus', 'LX', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (451, 'Audi', 'V8', 1992);
insert into car_data (id, car_make, car_model, car_model_year) values (452, 'Lexus', 'GS', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (453, 'Chevrolet', 'Aveo', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (454, 'Mazda', '626', 1991);
insert into car_data (id, car_make, car_model, car_model_year) values (455, 'Mazda', 'MX-5', 1990);
insert into car_data (id, car_make, car_model, car_model_year) values (456, 'Suzuki', 'Equator', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (457, 'Mazda', 'Mazdaspeed 3', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (458, 'Honda', 'Accord', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (459, 'Chrysler', 'Town & Country', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (460, 'Lexus', 'GS', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (461, 'Mercedes-Benz', 'C-Class', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (462, 'Cadillac', 'CTS', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (463, 'BMW', 'Z3', 1999);
insert into car_data (id, car_make, car_model, car_model_year) values (464, 'Ford', 'Ranger', 1995);
insert into car_data (id, car_make, car_model, car_model_year) values (465, 'Volvo', 'S80', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (466, 'GMC', 'Vandura G3500', 1995);
insert into car_data (id, car_make, car_model, car_model_year) values (467, 'Lincoln', 'MKZ', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (468, 'Lexus', 'ES', 1990);
insert into car_data (id, car_make, car_model, car_model_year) values (469, 'Alfa Romeo', 'Spider', 1994);
insert into car_data (id, car_make, car_model, car_model_year) values (470, 'Cadillac', 'SRX', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (471, 'Toyota', 'Prius', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (472, 'Cadillac', 'Escalade', 2010);
insert into car_data (id, car_make, car_model, car_model_year) values (473, 'Chevrolet', 'Silverado', 1999);
insert into car_data (id, car_make, car_model, car_model_year) values (474, 'Chevrolet', 'Malibu', 2002);
insert into car_data (id, car_make, car_model, car_model_year) values (475, 'Toyota', 'Celica', 2004);
insert into car_data (id, car_make, car_model, car_model_year) values (476, 'Mercury', 'Cougar', 1986);
insert into car_data (id, car_make, car_model, car_model_year) values (477, 'Mazda', 'Tribute', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (478, 'Audi', '90', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (479, 'Ford', 'E150', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (480, 'Maybach', '62', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (481, 'Pontiac', 'Safari', 1988);
insert into car_data (id, car_make, car_model, car_model_year) values (482, 'Lexus', 'RX', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (483, 'Suzuki', 'XL7', 2008);
insert into car_data (id, car_make, car_model, car_model_year) values (484, 'Mercury', 'Cougar', 1995);
insert into car_data (id, car_make, car_model, car_model_year) values (485, 'Pontiac', 'Trans Sport', 1998);
insert into car_data (id, car_make, car_model, car_model_year) values (486, 'Mitsubishi', 'Mirage', 1984);
insert into car_data (id, car_make, car_model, car_model_year) values (487, 'Ford', 'F250', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (488, 'Ford', 'Crown Victoria', 2009);
insert into car_data (id, car_make, car_model, car_model_year) values (489, 'Volkswagen', 'Golf', 2001);
insert into car_data (id, car_make, car_model, car_model_year) values (490, 'Mazda', 'B-Series', 1989);
insert into car_data (id, car_make, car_model, car_model_year) values (491, 'Porsche', '968', 1994);
insert into car_data (id, car_make, car_model, car_model_year) values (492, 'GMC', 'Yukon', 2003);
insert into car_data (id, car_make, car_model, car_model_year) values (493, 'Ford', 'F-Series', 2011);
insert into car_data (id, car_make, car_model, car_model_year) values (494, 'Jaguar', 'S-Type', 2007);
insert into car_data (id, car_make, car_model, car_model_year) values (495, 'Isuzu', 'VehiCROSS', 1999);
insert into car_data (id, car_make, car_model, car_model_year) values (496, 'Ford', 'Edge', 2012);
insert into car_data (id, car_make, car_model, car_model_year) values (497, 'Mitsubishi', 'RVR', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (498, 'Nissan', 'Pathfinder', 1994);
insert into car_data (id, car_make, car_model, car_model_year) values (499, 'Chevrolet', 'S10 Blazer', 1993);
insert into car_data (id, car_make, car_model, car_model_year) values (500, 'Lamborghini', 'Diablo', 1991);
